### ISSUE TITLE
sometimes client receives status code 304 and blank page

### ISSUE THREAD

**Issue by ahto** [addisonj/node-cacher#24]
I have pingdom checks enabled for my site and it alerts every once in a while that the site is down.
This is the response it gets:

    304 Not Modified
    Connection: close
    Status: 304 Not Modified
    X-Powered-By: Phusion Passenger Enterprise 5.0.4
    cache-control: max-age=300, must-revalidate
    date: Sat, 21 Mar 2015 11:18:55 GMT
    x-cacher-hit: true
    etag: W/"PppsnKgE23eklpIZcIvfFA=="
    Server: nginx + Phusion Passenger 5.0.4

From what i understand, the server shouldn't send 304 response unless the content matches what ever is cached client side. But pingdom bot shouldn't have anything cached from before.

I hit this today myself when browsing around. a browser that doesn't have any content cached client side receives status code 304 and no content at all. then after a while it goes back to normal.

Disabling cacher fixes the issue. I'm digging into the code but wanted to ask if you know about some fix for this already?

**Comment by ahto** [comment]
after digging around this is my current understanding.

in case of a cache miss, if client does HEAD request then what gets saved is a blank page.
Then if another client does GET request after that there is no content but it is a cache hit.

I can replicate it like this:
passenger start -p1337 #start webserver
echo 'flush_all' | nc localhost 11211 #clear memcached
curl -I http://localhost:1337/ #cache miss and save to cache
curl http://localhost:1337/ #cache hit but no content

    App 16540 stdout: PageCacher MISS - /
    App 16540 stdout: HEAD / 200 63.769 ms - 20778
    App 16540 stdout: PageCacher CACHE - [object Object]
    App 16540 stdout: PageCacher HIT - /
    [ 2015-03-22 16:41:23.9525 16479/7ffc2b7fe700 age/Hel/Req/ForwardResponse.cpp:168 ]: [Client 3-1] Application sent EOF before finishing response body: 0 bytes already read, 20778 bytes expected
    [ 2015-03-22 16:41:23.9526 16479/7ffc2b7fe700 Ser/Server.h:894 ]: [Client 3-1] Disconnecting client with error: application did not send a complete response
    App 16540 stdout: GET / 200 2.098 ms - 20778

the status code 304 maybe comes from the phusion passenger server, it has some smarts built in to caching layer. i'm not 100% sure about this.

**Comment by ahto** [comment]
workaround for the above issue.

    var cacher =  new Cacher(new CacherMemcached(...);
  
    cacher.genCacheKey = function(req) {
      return req.method+'_'+req.originalUrl;
    };

With this i cannot replicate the mixing of head and get requests anymore.

But, then clicking around i found another issue and it look like the one i see from before.

To replicate:
1. Use short time for cacher, for example cacheMinutes(1)
2. passenger start -p1337 #start webserver
3. use firefox and browse to http://localhost:1337, this will save the cached version to browsers own cache. make sure, reload the page ctrl+r
4. echo 'flush_all' | nc localhost 11211 #clear memcached
5. Now, browser cache has the page but memcached doesnt.
6. Wait for 1 minute and browse again to http://localhost:1337 but dont hit reload.
7. Then after that do full page reload ctrl+r and get a white page.

also memcached show this.

    $ echo 'get GET_/' | nc localhost 11211
    VALUE GET_/ 2 177
    {"statusCode":304,"content":"","headers":{"x-powered-by":"Express","cache-control":"max-age=60, must-revalidate","x-cacher-hit":"false","etag":"W/\"oG4sF7FhsfT2oWqryV0pag==\""}}
    END

**Comment by addisonj** [comment]
Awesome bug report should have some time this afternoon to take a closer
look and figure out what is going on.

I think express might be handling HEAD requests differently which is
throwing things off, thinking about it now is pretty obvious (it never
writes the body which,  Is how we hook in to cache the request)

I think the fix will just be not allowing head requests to fill the cache.

**Comment by addisonj** [comment]
@ahto try installing from this branch: https://github.com/addisonj/node-cacher/tree/no_head

I will try and whip up a test to capture the problem, but would let me know if that works for you.

**Comment by ahto** [comment]
Yeah this fix the mixing of head and get but i still see the behaviour that result into this content in memcached.

    zizzler@citadel:~$ echo 'get GET /' | nc localhost 11211
    VALUE / 2 177
    {"statusCode":304,"content":"","headers":{"x-powered-by":"Express","cache-control":"max-age=60, must-revalidate","x-cacher-hit":"false","etag":"W/\"5FlgEIgyBXffOSC1sBAr1Q==\""}}
    END

i may have some time this weekend to dig deeper.

**Comment by DeltaMeter** [comment]
Is this still being worked on?

**Comment by addisonj** [comment]
I was waiting for @ahto to see if he discovered anything else as it seems there may still be an issue?

I think the change to not cache HEAD requests makes sense and I just merged and published as 3.0.0 (as not caching HEAD requests is technically a breaking change)

I am going to close this issue but please reopen if you experience any problems of this same nature

**Comment by mluogh** [comment]
I'm still getting the blank page along with this error from Firefox:
"The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature."

**Comment by ernoaapa** [comment]
I have probably related issue. If browser send a GET request with `if-none-match` header (which contains the etag), our app responses with 304 and empty content because the etag were the up to date version of the content but now cache contains empty content.
Later on some other client might make a request to the same url without any etag, but cacher returns the empty response.

Sadly I don't have yet any idea how cache should handle etags and specially how I could clear old data from cache if I append the etag into the cache key.
